spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pulseapi
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    
telegram:
  bot:
    token: "7968923044:AAEkQQ8xM7-psv5fvk7C6r2tCI0cBr176c4"
    username: "ApiPulse027_bot"

api-pulse:
  server-url: http://localhost:8080
  access-token: eef80323-7c4d-47cf-8ffa-522497b6d3f4
  telegram-token: "7968923044:AAEkQQ8xM7-psv5fvk7C6r2tCI0cBr176c4"
  telegram-username: "ApiPulse027_bot"
  chat-id: "-4699186307"